name: Release Build

on:
  push:
    tags:
      - 'v*'

env:
  TZ: 'Europe/Berlin'
  LANG: 'de'
  CONFIGURATION: 'Release'
  CI_COMMIT_TAG: ${{ github.ref_name }}

jobs:
  prepare:
    runs-on: ubuntu

    defaults:
      run:
        shell: bash

    outputs:
      hostname: ${{ steps.parse.outputs.hostname }}

    steps:
      - name: Parse push event
        uses: actions/am-wd/parse-event@main
        id: parse


  build-test-deploy:
    needs: [ prepare ]
    runs-on: ubuntu

    defaults:
      run:
        shell: bash

    env:
      CI_SERVER_HOST: ${{ needs.prepare.outputs.hostname }}

    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.x
          cache: false

      - name: Checkout repository code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Restore tools
        run: |
          set -ex
          dotnet restore -v q
          dotnet tool install dotnet-reportgenerator-globaltool --tool-path /dotnet-tools
          dotnet tool install docfx --tool-path /dotnet-tools

      - name: Build solution
        run: |
          set -ex
          dotnet build -c ${CONFIGURATION} --nologo --restore --force --no-cache

      - name: Test solution
        run: |
          set -ex
          dotnet test -c ${CONFIGURATION} --no-build --nologo /p:CoverletOutputFormat=Cobertura
          /dotnet-tools/reportgenerator "-reports:${{ github.workspace }}/**/coverage.cobertura.xml" "-targetdir:/reports" "-reportType:TextSummary"
          cat /reports/Summary.txt

      - name: Build documentation
        env:
          DOCFX_SOURCE_REPOSITORY_URL: 'https://github.com/AM-WD/AMWD.Protocols.Modbus'
        run: |
          set -ex
          /dotnet-tools/docfx metadata docs/docfx.json
          /dotnet-tools/docfx build docs/docfx.json

      - name: Publish packages
        uses: actions/am-wd/publish-nuget@main
        with:
          api-key: ${{ secrets.NUGET_APIKEY }}
          source: https://api.nuget.org/v3/index.json
          package-name: 'AMWD.Protocols.Modbus'

      - name: Publish docs
        uses: actions/am-wd/deploy-ssh@main
        with:
          hostname: ${{ vars.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          local-path: ${{ github.workspace }}/docs/_site
          remote-path: /var/www/docs/modbus
          delete-unknown: true
